In [1]:
import pandas as pd

plant1 = pd.read_csv('./plant1_train.csv',parse_dates=['plant1_train.mea_ddhr'])
plant1.head(10)

,Unnamed: 0,plant1_train.mea_ddhr,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,plant1_train.tem_out_loc1,plant1_train.hum_out_loc1,plant1_train.cond_loc1,plant1_train.cond_loc2,plant1_train.cond_loc3
0,1,2016-04-01 00:00:00,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,9.0,42.0,0.0,0.0,0.0
1,2,2016-04-01 03:00:00,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,7.0,59.0,0.0,0.0,0.0
2,3,2016-04-01 06:00:00,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,6.0,56.0,0.0,0.0,0.0
3,4,2016-04-01 09:00:00,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,18.0,30.0,0.0,0.0,0.0
4,5,2016-04-01 12:00:00,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,18.0,20.0,0.0,0.0,0.0
5,6,2016-04-01 15:00:00,18.0,24.0,14.0,18.0,21.0,14.0,16.0,27.0,12.0,17.0,23.0,0.0,0.0,0.0
6,7,2016-04-01 18:00:00,17.0,28.0,14.0,17.0,29.0,14.0,15.0,38.0,12.0,12.0,52.0,0.0,0.0,0.0
7,8,2016-04-01 21:00:00,16.0,38.0,12.0,15.0,36.0,12.0,14.0,41.0,11.0,11.0,55.0,0.0,0.0,0.0
8,9,2016-04-02 00:00:00,15.0,41.0,12.0,14.0,43.0,12.0,13.0,49.0,11.0,10.0,57.0,0.0,0.0,0.0
9,10,2016-04-02 03:00:00,14.0,41.0,10.0,12.0,44.0,9.0,12.0,49.0,8.0,10.0,54.0,0.0,0.0,0.0

In [2]:
del plant1['Unnamed: 0']

In [3]:
plant1["year"] = plant1["plant1_train.mea_ddhr"].dt.year
plant1["month"] = plant1["plant1_train.mea_ddhr"].dt.month
plant1["day"] = plant1["plant1_train.mea_ddhr"].dt.day
plant1["hour"] = plant1["plant1_train.mea_ddhr"].dt.hour
plant1["minute"] = plant1["plant1_train.mea_ddhr"].dt.minute
plant1["second"] = plant1["plant1_train.mea_ddhr"].dt.second
plant1.head()

,plant1_train.mea_ddhr,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,...,plant1_train.hum_out_loc1,plant1_train.cond_loc1,plant1_train.cond_loc2,plant1_train.cond_loc3,year,month,day,hour,minute,second
0,2016-04-01 00:00:00,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,...,42.0,0.0,0.0,0.0,2016,4,1,0,0,0
1,2016-04-01 03:00:00,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,...,59.0,0.0,0.0,0.0,2016,4,1,3,0,0
2,2016-04-01 06:00:00,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,...,56.0,0.0,0.0,0.0,2016,4,1,6,0,0
3,2016-04-01 09:00:00,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,...,30.0,0.0,0.0,0.0,2016,4,1,9,0,0
4,2016-04-01 12:00:00,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,...,20.0,0.0,0.0,0.0,2016,4,1,12,0,0

In [4]:
plant1_del = plant1.dropna(axis=0)

In [5]:
Y1 = plant1_del[['plant1_train.cond_loc1']]
Y2 = plant1_del[['plant1_train.cond_loc2']]
Y3 = plant1_del[['plant1_train.cond_loc3']]
Y = plant1_del[['plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3']]
X = plant1_del.drop(['plant1_train.mea_ddhr','plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3'],axis=1)

In [6]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, Y1_train, Y1_test = train_test_split(X,Y1,test_size=0.2,shuffle=True)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X,Y2,test_size=0.2,shuffle=True)
X3_train, X3_test, Y3_train, Y3_test = train_test_split(X,Y3,test_size=0.2,shuffle=True)

In [7]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [8]:
X1_train = X1_train.values
X2_train = X2_train.values
X3_train = X3_train.values
Y1_train = Y1_train.values.ravel()
Y2_train = Y2_train.values.ravel()
Y3_train = Y3_train.values.ravel()

In [9]:
naive1 = GaussianNB()

In [10]:
naive1.fit(X1_train,Y1_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [11]:
from sklearn import metrics

In [12]:
pred1 = naive1.predict(X1_test)
print("loc1 훈련 세트 정확도: {:.3f}".format(naive1.score(X1_train, Y1_train)))
print("loc1 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y1_test,pred1)))

loc1 훈련 세트 정확도: 0.981
loc1 테스트 세트 정확도: 0.886

In [13]:
naive2 = GaussianNB()
naive2.fit(X2_train,Y2_train)
pred2 = naive2.predict(X2_test)
print("loc2 훈련 세트 정확도: {:.3f}".format(naive2.score(X2_train, Y2_train)))
print("loc2 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y2_test,pred2)))

loc2 훈련 세트 정확도: 0.975
loc2 테스트 세트 정확도: 0.910

In [14]:
naive3 = GaussianNB()
naive3.fit(X3_train,Y3_train)
pred3 = naive3.predict(X3_test)
print("loc3 훈련 세트 정확도: {:.3f}".format(naive3.score(X3_train, Y3_train)))
print("loc3 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y3_test,pred3)))

loc3 훈련 세트 정확도: 0.966
loc3 테스트 세트 정확도: 0.869

In [15]:
pred1_proba = naive1.predict_proba(X1_test)

In [16]:
print(pred1_proba)

[[1.00000000e+00 2.75085809e-58]
 [9.99982170e-01 1.78299492e-05]
 [1.00000000e+00 5.04127683e-24]
 ...
 [1.00000000e+00 6.42329085e-60]
 [1.00000000e+00 8.39023988e-31]
 [5.88843613e-02 9.41115639e-01]]