In [1]:
import pandas as pd

plant1 = pd.read_csv('./plant1_train.csv',parse_dates=['plant1_train.mea_ddhr'])
plant1.head(10)

,Unnamed: 0,plant1_train.mea_ddhr,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,plant1_train.tem_out_loc1,plant1_train.hum_out_loc1,plant1_train.cond_loc1,plant1_train.cond_loc2,plant1_train.cond_loc3
0,1,2016-04-01 00:00:00,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,9.0,42.0,0.0,0.0,0.0
1,2,2016-04-01 03:00:00,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,7.0,59.0,0.0,0.0,0.0
2,3,2016-04-01 06:00:00,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,6.0,56.0,0.0,0.0,0.0
3,4,2016-04-01 09:00:00,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,18.0,30.0,0.0,0.0,0.0
4,5,2016-04-01 12:00:00,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,18.0,20.0,0.0,0.0,0.0
5,6,2016-04-01 15:00:00,18.0,24.0,14.0,18.0,21.0,14.0,16.0,27.0,12.0,17.0,23.0,0.0,0.0,0.0
6,7,2016-04-01 18:00:00,17.0,28.0,14.0,17.0,29.0,14.0,15.0,38.0,12.0,12.0,52.0,0.0,0.0,0.0
7,8,2016-04-01 21:00:00,16.0,38.0,12.0,15.0,36.0,12.0,14.0,41.0,11.0,11.0,55.0,0.0,0.0,0.0
8,9,2016-04-02 00:00:00,15.0,41.0,12.0,14.0,43.0,12.0,13.0,49.0,11.0,10.0,57.0,0.0,0.0,0.0
9,10,2016-04-02 03:00:00,14.0,41.0,10.0,12.0,44.0,9.0,12.0,49.0,8.0,10.0,54.0,0.0,0.0,0.0

In [2]:
plant1.columns

Index(['Unnamed: 0', 'plant1_train.mea_ddhr', 'plant1_train.tem_in_loc1',
       'plant1_train.hum_in_loc1', 'plant1_train.tem_coil_loc1',
       'plant1_train.tem_in_loc2', 'plant1_train.hum_in_loc2',
       'plant1_train.tem_coil_loc2', 'plant1_train.tem_in_loc3',
       'plant1_train.hum_in_loc3', 'plant1_train.tem_coil_loc3',
       'plant1_train.tem_out_loc1', 'plant1_train.hum_out_loc1',
       'plant1_train.cond_loc1', 'plant1_train.cond_loc2',
       'plant1_train.cond_loc3'],
      dtype='object')

In [3]:
del plant1['Unnamed: 0']

In [4]:
plant1["year"] = plant1["plant1_train.mea_ddhr"].dt.year
plant1["month"] = plant1["plant1_train.mea_ddhr"].dt.month
plant1["day"] = plant1["plant1_train.mea_ddhr"].dt.day
plant1["hour"] = plant1["plant1_train.mea_ddhr"].dt.hour
plant1["minute"] = plant1["plant1_train.mea_ddhr"].dt.minute
plant1["second"] = plant1["plant1_train.mea_ddhr"].dt.second
plant1.head()

,plant1_train.mea_ddhr,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,...,plant1_train.hum_out_loc1,plant1_train.cond_loc1,plant1_train.cond_loc2,plant1_train.cond_loc3,year,month,day,hour,minute,second
0,2016-04-01 00:00:00,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,...,42.0,0.0,0.0,0.0,2016,4,1,0,0,0
1,2016-04-01 03:00:00,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,...,59.0,0.0,0.0,0.0,2016,4,1,3,0,0
2,2016-04-01 06:00:00,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,...,56.0,0.0,0.0,0.0,2016,4,1,6,0,0
3,2016-04-01 09:00:00,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,...,30.0,0.0,0.0,0.0,2016,4,1,9,0,0
4,2016-04-01 12:00:00,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,...,20.0,0.0,0.0,0.0,2016,4,1,12,0,0

In [5]:
plant1_del = plant1.dropna(axis=0)

In [6]:
plant1_del.head(10)

,plant1_train.mea_ddhr,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,...,plant1_train.hum_out_loc1,plant1_train.cond_loc1,plant1_train.cond_loc2,plant1_train.cond_loc3,year,month,day,hour,minute,second
0,2016-04-01 00:00:00,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,...,42.0,0.0,0.0,0.0,2016,4,1,0,0,0
1,2016-04-01 03:00:00,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,...,59.0,0.0,0.0,0.0,2016,4,1,3,0,0
2,2016-04-01 06:00:00,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,...,56.0,0.0,0.0,0.0,2016,4,1,6,0,0
3,2016-04-01 09:00:00,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,...,30.0,0.0,0.0,0.0,2016,4,1,9,0,0
4,2016-04-01 12:00:00,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,...,20.0,0.0,0.0,0.0,2016,4,1,12,0,0
5,2016-04-01 15:00:00,18.0,24.0,14.0,18.0,21.0,14.0,16.0,27.0,12.0,...,23.0,0.0,0.0,0.0,2016,4,1,15,0,0
6,2016-04-01 18:00:00,17.0,28.0,14.0,17.0,29.0,14.0,15.0,38.0,12.0,...,52.0,0.0,0.0,0.0,2016,4,1,18,0,0
7,2016-04-01 21:00:00,16.0,38.0,12.0,15.0,36.0,12.0,14.0,41.0,11.0,...,55.0,0.0,0.0,0.0,2016,4,1,21,0,0
8,2016-04-02 00:00:00,15.0,41.0,12.0,14.0,43.0,12.0,13.0,49.0,11.0,...,57.0,0.0,0.0,0.0,2016,4,2,0,0,0
9,2016-04-02 03:00:00,14.0,41.0,10.0,12.0,44.0,9.0,12.0,49.0,8.0,...,54.0,0.0,0.0,0.0,2016,4,2,3,0,0

In [7]:
print(plant1_del.shape, plant1.shape)

(57854, 21) (58749, 21)

In [8]:
Y1 = plant1_del[['plant1_train.cond_loc1']]
Y2 = plant1_del[['plant1_train.cond_loc2']]
Y3 = plant1_del[['plant1_train.cond_loc3']]
Y = plant1_del[['plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3']]
X = plant1_del.drop(['plant1_train.mea_ddhr','plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3'],axis=1)

In [9]:
X.head()

,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,plant1_train.tem_out_loc1,plant1_train.hum_out_loc1,year,month,day,hour,minute,second
0,16.0,24.0,11.0,14.0,23.0,11.0,13.0,32.0,10.0,9.0,42.0,2016,4,1,0,0,0
1,14.0,28.0,10.0,12.0,32.0,9.0,11.0,42.0,7.0,7.0,59.0,2016,4,1,3,0,0
2,13.0,33.0,10.0,11.0,37.0,9.0,10.0,44.0,7.0,6.0,56.0,2016,4,1,6,0,0
3,13.0,33.0,10.0,11.0,35.0,9.0,10.0,41.0,8.0,18.0,30.0,2016,4,1,9,0,0
4,16.0,28.0,10.0,15.0,27.0,11.0,14.0,30.0,9.0,18.0,20.0,2016,4,1,12,0,0

In [10]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, Y1_train, Y1_test = train_test_split(X,Y1,test_size=0.2,shuffle=True)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X,Y2,test_size=0.2,shuffle=True)
X3_train, X3_test, Y3_train, Y3_test = train_test_split(X,Y3,test_size=0.2,shuffle=True)

In [11]:
X1_train.head()

,plant1_train.tem_in_loc1,plant1_train.hum_in_loc1,plant1_train.tem_coil_loc1,plant1_train.tem_in_loc2,plant1_train.hum_in_loc2,plant1_train.tem_coil_loc2,plant1_train.tem_in_loc3,plant1_train.hum_in_loc3,plant1_train.tem_coil_loc3,plant1_train.tem_out_loc1,plant1_train.hum_out_loc1,year,month,day,hour,minute,second
6972,31.12,71.83,29.98,29.90,75.79,29.71,29.14,78.69,29.29,27.25,85.23,2017,7,22,3,0,0
50167,6.34,30.98,6.21,5.45,30.62,4.60,3.80,36.29,3.19,0.48,38.28,2019,1,31,9,40,0
12534,7.95,61.20,7.96,5.97,70.85,6.93,4.90,76.04,5.83,0.63,93.86,2018,3,12,4,0,0
7560,27.52,74.24,26.81,26.73,77.11,26.54,25.69,81.56,26.09,23.64,88.03,2017,8,15,15,0,0
18104,28.04,43.50,25.44,27.03,51.77,24.52,24.93,59.49,24.06,21.05,69.87,2018,6,21,17,0,0

In [12]:
from sklearn import svm
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics

In [13]:
X1_train = X1_train.values
X2_train = X2_train.values
X3_train = X3_train.values
Y1_train = Y1_train.values.ravel()
Y2_train = Y2_train.values.ravel()
Y3_train = Y3_train.values.ravel()
print(X1_train.shape,Y1_train.shape)

(46283, 17) (46283,)

In [14]:
clf1 = svm.SVC(kernel='linear')
clf1.fit(X1_train,Y1_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
pred1 = clf1.predict(X1_test)
print("loc1 훈련 세트 정확도: {:.3f}".format(clf1.score(X1_train, Y1_train)))
print("loc1 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y1_test,pred1)))

loc1 훈련 세트 정확도: 1.000
loc1 테스트 세트 정확도: 0.963

In [16]:
clf2 = svm.SVC(kernel='linear')
clf2.fit(X2_train,Y2_train)
pred2 = clf2.predict(X2_test)
print("loc2 훈련 세트 정확도: {:.3f}".format(clf2.score(X2_train, Y2_train)))
print("loc2 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y2_test,pred2)))

loc2 훈련 세트 정확도: 1.000
loc2 테스트 세트 정확도: 0.985

In [17]:
clf3 = svm.SVC(kernel='linear')
clf3.fit(X3_train,Y3_train)
pred3 = clf2.predict(X3_test)
print("loc3 훈련 세트 정확도: {:.3f}".format(clf3.score(X3_train, Y3_train)))
print("loc3 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y3_test,pred3)))

loc3 훈련 세트 정확도: 1.000
loc3 테스트 세트 정확도: 0.892

In [18]:
from sklearn.metrics import classification_report

target_names = ['0','1']
print(classification_report(Y1_test, pred1, target_names = target_names,zero_division=0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     11517
           1       0.96      0.93      0.94        54

    accuracy                           1.00     11571
   macro avg       0.98      0.96      0.97     11571
weighted avg       1.00      1.00      1.00     11571